#!/usr/bin/env node
// Derive the release-pace scoreboard (data/pace.json) from data/releases/.
//
//   node scripts/compute-pace.mjs                                  # 2026-08-24 → today
//   node scripts/compute-pace.mjs --from 2026-08-24 --to 2026-10-08
//   node scripts/compute-pace.mjs --stdout                         # print instead of writing
//
// Rules (METHODOLOGY.md, "Release-pace scoreboard"):
//   - count new features NAMED in release notes dated inside the window;
//   - fixes, speed-ups and reliability items are not counted, for anyone;
//   - a release whose notes repeat the previous release word for word adds nothing;
//   - boilerplate ("Bug fixes and improvements") names nothing and adds nothing;
//   - a release nobody has classified yet is listed under `pendingReview`
//     and adds nothing until a person classifies it.
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, loadApps, readJsonIfExists, writeJson, args, today } from './lib.mjs';

export const DEFAULT_FROM = '2026-08-24';

export function computePace({ from = DEFAULT_FROM, to = today() } = {}) {
  const apps = loadApps();
  const crossFiles = fs.readdirSync(path.join(ROOT, 'data')).filter((f) => /^pace-crosscheck-.*\.json$/.test(f)).sort();
  const cross = crossFiles.map((f) => ({ file: `data/${f}`, ...readJsonIfExists(`data/${f}`) }));
  const inWin = (d) => d >= from && d <= to;

  const rows = apps.map((app) => {
    const store = readJsonIfExists(`data/releases/${app.id}.json`);
    const storeInWin = (store?.releases ?? []).filter((r) => inWin(r.date));
    const row = {
      app: app.id,
      name: app.name,
      newFeatures: 0,
      basis: app.paceSource === 'app-store' ? 'App Store release notes' : 'In-app What’s New (self-reported)',
      appStoreReleasesInWindow: storeInWin.length,
      lastAppStoreRelease: store?.releases?.map((r) => r.date).sort().at(-1) ?? null,
      dataThrough: null,
      counted: [],
      notCounted: { fix: 0, 'speed or reliability': 0, repeatedNotes: 0, boilerplate: 0 },
      pendingReview: [],
    };

    if (app.paceSource === 'app-store') {
      row.dataThrough = store?.fetchedAt ?? null;
      for (const r of [...storeInWin].sort((a, b) => a.date.localeCompare(b.date))) {
        if (r.repeatsPreviousNotes) { row.notCounted.repeatedNotes++; continue; }
        if (r.generic) { row.notCounted.boilerplate++; continue; }
        if (r.features === null) { row.pendingReview.push({ version: r.version, date: r.date }); continue; }
        for (const f of r.features) row.counted.push({ date: r.date, version: r.version, feature: f });
        for (const n of r.notCounted ?? []) row.notCounted[n.reason] = (row.notCounted[n.reason] ?? 0) + 1;
      }
    } else if (app.paceSource === 'in-app-whats-new') {
      const wn = readJsonIfExists(`data/releases/${app.id}-whats-new.json`);
      row.dataThrough = wn?.fetchedAt ?? null;
      const entries = (wn?.entries ?? []).filter((e) => inWin(e.date)).sort((a, b) => a.date.localeCompare(b.date) || a.build - b.build);
      row.whatsNewEntriesInWindow = entries.length;
      row.notCounted = { improved: 0, fixed: 0 };
      for (const e of entries) {
        for (const f of e.new) row.counted.push({ date: e.date, version: `${e.version} (${e.build})`, feature: f });
        row.notCounted.improved += e.improvedCount;
        row.notCounted.fixed += e.fixedCount;
      }
      if (store?.releases?.length) row.appStoreNote = 'App Store releases are listed for comparison; this app’s count comes from its in-app What’s New, which also covers over-the-air updates.';
    }
    row.newFeatures = row.counted.length;
    if (row.dataThrough && row.dataThrough < to) row.caveat = `Data collected through ${row.dataThrough}; anything after that is not counted.`;

    // Things found outside the release notes during a manual cross-check (never counted).
    const outside = cross.flatMap((c) => (c.apps ?? []).filter((a) => a.app === app.id).flatMap((a) => (a.shippedInWindow ?? []).map((s) => ({ ...s, source: c.file }))));
    if (outside.length) row.foundOutsideReleaseNotes = outside;
    return row;
  });

  return {
    description: 'Release-pace scoreboard: new features named in release notes inside the window. Generated by scripts/compute-pace.mjs from data/releases/; do not edit by hand.',
    window: { from, to },
    rules: [
      'Counts new features named in release notes dated inside the window.',
      'Fixes, speed-ups and reliability items are not counted, for any app.',
      'A release whose notes repeat the previous release word for word adds nothing.',
      'Boilerplate such as "Bug fixes and improvements" names nothing and adds nothing.',
      'Where a note is ambiguous between new and improved, a competitor’s item is counted as new.',
      'Releases not yet classified by a person are listed under pendingReview and add nothing.',
      'notCounted tallies are for transparency only and are not comparable between apps: fix lines in App Store notes were not itemized exhaustively.',
    ],
    apps: rows,
  };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(ROOT, 'scripts/compute-pace.mjs');
if (isMain) {
  const opt = args();
  const pace = computePace({ from: opt.from || DEFAULT_FROM, to: opt.to || today() });
  if (opt.stdout) console.log(JSON.stringify(pace, null, 2));
  else writeJson('data/pace.json', pace);
  for (const r of pace.apps) {
    const pend = r.pendingReview.length ? `, ${r.pendingReview.length} release(s) awaiting review` : '';
    console.error(`${r.name.padEnd(7)} ${String(r.newFeatures).padStart(4)} new features (${r.basis})${pend}`);
  }
}
